# Generated by Django 3.1.6 on 2021-02-10 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mitienda.bill')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mitienda.product')),
            ],
        ),
    ]
