# Generated by Django 3.1.6 on 2021-02-10 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0002_billproduct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='billproduct',
            name='product_id',
            field=models.ManyToManyField(to='mitienda.Product'),
        ),
    ]
