# Generated by Django 3.1.6 on 2021-02-10 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mitienda', '0004_auto_20210210_0516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billproduct',
            name='product_id',
        ),
        migrations.AddField(
            model_name='billproduct',
            name='product_id',
            field=models.ManyToManyField(to='mitienda.Product'),
        ),
    ]
